docs/KustoSink.md
docs/KustoSource.md
pom.xml
src/main/scala/com/microsoft/kusto/spark/Sample/KustoConnectorDemo.scala
src/main/scala/com/microsoft/kusto/spark/Sample/SimpleKustoDataSource.scala
src/main/scala/com/microsoft/kusto/spark/Sample/pyKusto.py
src/main/scala/com/microsoft/kusto/spark/datasink/KustoSinkProvider.scala
src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
src/main/scala/com/microsoft/kusto/spark/datasource/DefaultSource.scala
src/main/scala/com/microsoft/kusto/spark/datasource/KustoOptions.scala
src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
src/main/scala/com/microsoft/kusto/spark/datasource/KustoResponseDeserializer.scala
src/main/scala/com/microsoft/kusto/spark/sql/extension/SparkExtension.scala
src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
src/main/scala/com/microsoft/kusto/spark/utils/KeyVaultADALAuthenticator.scala
src/main/scala/com/microsoft/kusto/spark/utils/KeyVaultUtils.scala
src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
src/main/scala/com/microsoft/kusto/spark/utils/KustoQueryUtils.scala
src/test/scala/com/microsoft/kusto/spark/KustoQueryUtilsTest.scala
src/test/scala/com/microsoft/kusto/spark/KustoSinkBatchE2E.scala
src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
src/test/scala/com/microsoft/kusto/spark/KustoSourceTests.scala

Note: RDD is not created.
Instead, data is parallel-exported.
If you're up to F2F review just ask :)
Below is a TODO-list that mention some items not covered in this review, on top of planned items such as pruned/filtered scan:
----------------------------------
Add the possibility to specify multiple storage accounts
• Add possibility to configure storage parameters externally as in https://docs.databricks.com/spark/latest/data-sources/azure/azure-storage.html#access-azure-blob-storage-using-the-rdd-api (and not by the connector every time as now)
• Review Redshift, Kafka etc. Finalize the decision whether KustoRDD implementation is required
• Check parquet format partitioning options and consider exposing them 
• Add Databricks example, including deleting transient storage
• Consider: …

Add scalable read via blob storage.

---

connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoConstants.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala

Fixes the following (unless I don't read the code correctly):
- All rows must be converted to csv. Originally the row that lead to cross maxBlobSize limit was not converted
- Al non-empty blobs must be finalized. Originally the blob that was currently written (and not added to the list of blobs to ingest) was not finalized
Also fix incorrect setting of the export file size limit in scalable read.
Changes in Source E2E will be reverted before merging to dev, please ignore

Fix writer skipping rows

---

connector/pom.xml

Addresses a known high severity security vulnerability detected in com.fasterxml.jackson.core:jackson-databind >= 2.8.0, < 2.8.11.2

Update Jackson to fix security vulnerability

---

connector/pom.xml
connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoTempIngestStorageCache.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoAzureFsSetupCache.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoQueryUtils.scala
connector/src/test/scala/com/microsoft/kusto/spark/KustoQueryUtilsTest.scala
connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkBatchE2E.scala
connector/src/test/scala/com/microsoft/kusto/spark/KustoTestUtils.scala
connector/src/test/scala/com/microsoft/kusto/spark/KustoWriterTests.scala

Parse table schema in kusto, and get the result as rows of name/csl-type/type.
This is both more efficient and reduces dependency on Jackson-core library.
Also, for query-schema it is sufficient to take 0 (instead of take 1).
All changes are pending validation

Parse table schema in Kusto

---

connector/pom.xml
connector/src/main/scala/com/microsoft/kusto/spark/common/KustoOptions.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/DefaultSource.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoConstants.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkTests.scala

small changes in the reading part:
better conversion to rdd 
setting the connector as insertable (enable usage of sql INSERT command)
adding equals method (should be used by spark to cache results)

set connector as insertable

---

connector/src/main/resources/app.properties
connector/src/main/scala/com/microsoft/kusto/spark/common/KustoOptions.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/DefaultSource.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoSourceOptions.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClientCache.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoConstants.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceTests.scala

Support non-public domains - writing and reading
---
**Features:**
- Added new option 
-  KUSTO_BLOB_STORAGE_ENDPOINT_SUFFIX "blobStorageEndpointSuffix" - when providing the storage yourself and using storage key for storage parameters, user can provide this option so that the created config will use the right domain
**Fixes:**
- Non-public domains were not parsed right
- Extract domain from blob SAS so that it is set right to the spark config
This goes along with our current Java support for authentication providing login url of the cloud in the environment variable : AadAuthorityUri

Support non-public domains

---

connector/pom.xml
connector/src/main/resources/app.properties
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClientCache.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceTests.scala
pom.xml

Using the config file we just added does not work on databricks if the library is taken from a local JAR
---
**Features:**
- new java version
**Fixes:**
- Default config values (used for parsing cluster URL)

Default config values + new java version

---

connector/src/main/scala/com/microsoft/kusto/spark/common/KustoOptions.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoSinkOptions.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/DefaultSource.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
docs/KustoSink.md
docs/KustoSource.md
pom.xml

operationId 
---
Setting operationId to easy track the operation on the spark logs and for reading - set as clientRequestId, for write: set as part of the staging table name  
**Features:**
- New option - 'operationId'

Setting operationId to easy track the operation

---

connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
pom.xml

In both Read and Write operation we failed on polling the operation status for every kind of exception. In read java client now returns if failure is permanent and if so we stop the polling, in write we continue polling if failure is from StroageException.
** Bug fix **
- Catch transient exceptions on status polling

Catch transient exceptions on status polling

---

connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala

If the connector couldn't delete the temporary table it used to suppress it.
When the connector starts it has an initial check for old tables - this check did not include hidden tables (which we moved to using at some point) and also it could delete new tables.
---
- Throw on temporary table deletion failure
**Fixes:**
- Initial cleanup of old temporary tables (older than three days)

Fix cleanup tables + table deletion exception should throw

---

connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoConstants.scala
connector/src/test/scala/com/microsoft/kusto/spark/KustoClientTests.scala

IngestIfNotExists tags can't be part of the regular flow as the data is ingested by multiple partitions into a staging table.
The solution here is dealing with the tags before and after the ingestion: First check the table before the ingestion into the staging table so as to skip it at all if the ingestBy tags itersect with the IngestIfNotExists ones. Second - when merging the tables - we do it in a single command that takes into consideration the current tags at this stage.
**Fixes:**
- Handle ingestIfNotExists tags

Handle ingestIfNotExists tags

---

connector/pom.xml
connector/scalastyle_config.xml
connector/src/main/scala/com/microsoft/kusto/spark/common/KustoOptions.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoSink.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoSinkProvider.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/DefaultSource.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoSourceOptions.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala

ClientRequstProperties option can be used on write operations (used for schema check operation, table creation and move extents)
Transient errors check on extents move retry + specific handling of timeout until changed from SDK side

Add ClientRequstProperties to Write + transient errors check on extents move retry

---

README.md
connector/src/main/scala/com/microsoft/kusto/spark/utils/DataTypeMapping.scala
connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
docs/Spark-Kusto DataTypes mapping.md
pom.xml

Kusto decimals are effectively floating point while Scala/Java are fixed point. Large decimals in Kusto are truncated or are marked as null in Spark  because we use 20,14 as Precision and scale.
The PR addresses this by using the Spark default scale (38,18) .  This is same Precision and Scale that in Parquet exports in ADX as well
**Fixes:**
- Change Decimal types to use 38,18 as the precision and scale (In line with the default in spark framework)

* Fix decimals to new scales 38,18 the default in Spark

---

connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala

Changes:
When creating buildScan operation, if the user explicitly uses the ForceSingleMode operation , always honor the single mode and do not fallback to distributed mode. This means that if ForceSingleMode is used and the query fails or times out the source operation will fail without fallback
In the earlier revision, if the ForcesingleMode is specified and the query fails, it will fallback to the ForceDistributedMode
Fixes issue #261

Fix Issue #261

---

connector/src/main/scala/com/microsoft/kusto/spark/common/KustoOptions.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/DefaultSource.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoSourceOptions.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/TransientStorageParameters.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
connector/src/test/scala/com/microsoft/kusto/spark/KustoBlobAccessE2E.scala
connector/src/test/scala/com/microsoft/kusto/spark/utils/CslCommandsGeneratorTest.scala
connector/src/test/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtilsTest.scala
docs/KustoSink.md
docs/KustoSource.md

Add support for passing in additional options when using the **.export** model in ForceDistributedMode. Since there are lot of new options that can be passed in this is a map of options, passed in as a JSON
for example 
**'{"exportOption1":"e1", "exportOptionForCompression":"none"}'** 
When the **.export** is called in the ForceDistributedMode or because of limits getting hit these options will be added in the **with** clause
**.export async ..... with ( ..... , exportOption1="e1",exportOptionForCompression="none")**
Idea would be to take this as a KustoSourceOption and then validate it (has to be a proper name value pair as a parsable JSON)
and then use the map to provide options in export
Tests are WIP
**Features:**
- #276

Expose Export options for distributed mode

---

README.md
connector/pom.xml
connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoSourceOptions.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
docs/KustoSource.md
pom.xml

Bug fix:
Disable new parquet writer on distributed reading if spark version is smaller than 3.3.0

Bug fix: distributed read could fail with Unsupported encoding: DELTA_BYTE_ARRAY 

---

connector/src/main/scala/com/microsoft/kusto/spark/authentication/KustoAuthentication.scala
connector/src/main/scala/com/microsoft/kusto/spark/common/KustoOptions.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClientCache.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
connector/src/test/scala/com/microsoft/kusto/spark/KustoAuthenticationTestE2E.scala
docs/Authentication.md

_[managed identity](https://learn.microsoft.com/azure/active-directory/managed-identities-azure-resources/overview) authentication support_
---
- None
**Features:**
- Managed Identity authentication
**Fixes:**
- None
Examples:
1) If System-assigned Managed Identity( no need to pass KUSTO_MANAGED_CLIENT_ID):
```
df.write
.format("com.microsoft.kusto.spark.datasource")
.format("com.microsoft.kusto.spark.datasource")
.option(KustoSinkOptions.KUSTO_CLUSTER, "MyCluster")
.option(KustoSinkOptions.KUSTO_DATABASE, "MyDatabase")
.option(KustoSinkOptions.KUSTO_TABLE, "MyTable")
.option(KustoSinkOptions.KUSTO_MANAGED_IDENTITY_AUTH, true.toString)
.mode(SaveMode.Append)
.save()
```
2) User-assigned Managed identity:
```
df.write
.format("com.microsoft.kusto.spark.datasource") …
```

Added Managed Identity authentication 

---

connector/pom.xml
connector/src/test/scala/com/microsoft/kusto/spark/utils/KustoAzureFsSetupCacheTest.scala
pom.xml

For the JDK 11 compat to work with scala 2.4. We will need to use scala 2.12.

Bugfix/sparkversion change2.4

---

connector/pom.xml
connector/src/main/resources/log4j.properties
connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasink/SparkIngestionProperties.scala
connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
connector/src/test/scala/com/microsoft/kusto/spark/utils/SparkIngestionPropertiesTest.scala
pom.xml
samples/pom.xml

**Fixes:**
- Spark ingestion properties clone was bad, impacted only users that use flashImmediately
- Missing dependency on old azure storage

Spark ingestion properties clone

---

.github/workflows/build.yml
connector/pom.xml
connector/src/main/scala/com/microsoft/kusto/spark/exceptions/NoStorageContainersException.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/ContainerProvider.scala
connector/src/test/scala/com/microsoft/kusto/spark/ExtendedKustoClientTests.scala
connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkStreamingE2E.scala
connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
connector/src/test/scala/com/microsoft/kusto/spark/utils/ContainerProviderTest.scala
connector/src/test/scala/com/microsoft/kusto/spark/utils/KustoAzureFsSetupCacheTest.scala
pom.xml

Added retry mechanism for the cases when no storage is returned. 
errortrace:
```
ERROR: Query termination received for [id=96300c8c-6de5-46bc-816e-ce9e78bd2e53, runId=722c6239-67b9-4182-b3b4-3c33c1e37f69], with exception: py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: Traceback (most recent call last):
File "/databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 617, in _call_proxy
return_value = getattr(self.pool[obj_id], method)(*params)
File "/databricks/spark/python/pyspark/sql/utils.py", line 117, in call
raise e
File "/databricks/spark/python/pyspark/sql/utils.py", line 114, in call
self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
File "/Workspace/Repos/aisfenix/adx-ingest/src/euvdb/jobs_uc.py", line 388, in …
```

Retry for ingestion Resources

---

connector/scalastyle_config.xml
connector/src/main/scala/com/microsoft/kusto/spark/datasink/FinalizeHelper.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/ContainerProvider.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/ExtendedKustoClient.scala
connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala

** New Feat **
* Client activity id now has the following scheme : "requestID;activityName;UUID;1"

New clientRequestID per call
