Azure/azure-kusto-spark

- docs/CHANGELIST
- docs/KustoSource.md
- src/main/scala/com/microsoft/kusto/spark/Sample/KustoConnectorDemo.scala
- src/main/scala/com/microsoft/kusto/spark/Sample/pyKusto.py
- src/main/scala/com/microsoft/kusto/spark/datasource/DefaultSource.scala
- src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
- src/main/scala/com/microsoft/kusto/spark/sql/extension/SparkExtension.scala
- src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
- src/test/scala/com/microsoft/kusto/spark/KustoBlobAccessE2E.scala
- src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
- src/test/scala/com/microsoft/kusto/spark/KustoSourceTests.scala
remove table option from source reading and add a python sample
> remove table option from source reading and add a python sample

- pom.xml
- src/main/scala/com/microsoft/kusto/spark/datasink/KustoSink.scala
- src/main/scala/com/microsoft/kusto/spark/datasink/KustoSinkProvider.scala
- src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- src/main/scala/com/microsoft/kusto/spark/datasink/TempStorageCache.scala
- src/main/scala/com/microsoft/kusto/spark/datasource/DefaultSource.scala
- src/main/scala/com/microsoft/kusto/spark/datasource/KustoOptions.scala
- src/main/scala/com/microsoft/kusto/spark/utils/KeyVaultADALAuthenticator.scala
- src/main/scala/com/microsoft/kusto/spark/utils/KeyVaultUtils.scala
- src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
- src/test/scala/com/microsoft/kusto/spark/KustoSinkBatchE2E.scala
- src/test/scala/com/microsoft/kusto/spark/KustoSinkTests.scala
- src/test/scala/com/microsoft/kusto/spark/keyVaultAuthenticationTest.scala
keyVault authentication + organize kustoOptions in categories
> keyVault authentication + organize kustoOptions in categories

- .gitignore
- README.md
Adding/Changing the following sections in the Readme:
- Contribution
- Samples
- Support
- Other SDKs
> Modify readme

- .gitignore
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/DefaultSource.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoFilter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoOptions.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KeyVaultADALAuthenticator.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KeyVaultUtils.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoFilterTests.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoPruneAndFilterE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceTests.scala
- docs/Authentication.md
- docs/KustoSink.md
- docs/KustoSource.md
> Add pruning and filtering to the read-connector

- README.md
- connector/pom.xml
- docs/CHANGELIST
- samples/pom.xml
> Update change log with main changes. 

- docs/KustoSource.md
Missing documentation on 'KUSTO_BLOB_SET_FS_CONFIG' option.
> Add KUSTO_BLOB_SET_FS_CONFIG to KustoSource.md

- connector/src/main/scala/com/microsoft/kusto/spark/utils/DeviceAuthentication.scala
fix clipboard copy that failed if no screen is detected
> fix clipboard copy that failed if no screen is detected

- README.md
- connector/src/test/scala/com/microsoft/kusto/spark/KustoAthenticationTest.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoBlobAccessE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoPruneAndFilterE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkBatchE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
- docs/Authentication.md
- docs/KustoSink.md
Also fix readme to specify the data/ingest client version explicitely
> Documentation and tests minor cleanup

- samples/src/main/scala/KustoConnectorDemo.scala
This change was already committed on master, so it will make dev aligned to master
> Remove a misleading comment

- connector/pom.xml
- pom.xml
- samples/pom.xml
The pipeline https://msazure.visualstudio.com/One/_build/results?buildId=22159911 was updated accordingly, to have the artifacts published on the pipeline.
> Add source plugin

- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
> device token fix

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/DataTypeMapping.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoWriterTests.scala
Adding support for MapData types
> Adding support for MapData types

- connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
> fix-shcemashowcommand

- connector/pom.xml
Fix security vulnerability: Sechttps://nvd.nist.gov/vuln/detail/CVE-2019-12086
> Update jackson databind

- connector/pom.xml
- pom.xml
> fix-dependencies-keyvault

- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
> DontFailOnCountTimeout

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoQueryUtils.scala
Bug fix - write size was taken as mega * mega = 0 as integer instead of being taken from user input
> Fix write size

- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoConstants.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
- pom.xml
Estimate size and fallback to export if fail with simple query
> Estimate size and fallback to export if fail with simple query 

- connector/pom.xml
Log4j was found as unsafe library
> Use sl4j instead of log4j

- connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoPruneAndFilterE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkBatchE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkStreamingE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
Create temporary tables as hidden
> Hide table

- pom.xml
> bump-version-v1.1.1

- connector/src/main/scala/com/microsoft/kusto/spark/utils/DeviceAuthentication.scala
- docs/Authentication.md
Docs and open device auth method as public
> Docs and make device auth method public 

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
Database with whitespaces failed for blob name includes it
> Normalize database name

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/Writers.scala
- connector/src/test/scala/com/microsoft/kusto/spark/WriterTests.scala
> Empty strings in structs

- README.md
- connector/src/test/scala/com/microsoft/kusto/spark/WriterTests.scala
- pom.xml
> bump version

- samples/src/main/python/pyKusto.py
changed 
deviceCodeMessage = deviceAuth.getDeviceCodeMassage() 
to 
deviceCodeMessage = deviceAuth.getDeviceCodeMessage()
> Fixed the typo for fixing Device Authentication code sample

- README.md
- pom.xml
> bump-version-1.1.5

- connector/pom.xml
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/SparkIngestionProperties.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoResponseDeserializer.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ContainerProvider.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoConstants.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoAuthenticationTestE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoBlobAccessE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoPruneAndFilterE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkBatchE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceTests.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoTestUtils.scala
- connector/src/test/scala/com/microsoft/kusto/spark/WriterTests.scala
- pom.xml
Using java SDK version 2
---
- The java sdk version changed to version 2 which has a new API
> New sdk version

- connector/pom.xml
Update adal4j version
---
- Update adal4j version
> Update adal4j version

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/RowCSVWriterUtils.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ContainerProvider.scala
- connector/src/test/scala/com/microsoft/kusto/spark/WriterTests.scala
Write Decimal type as string without scientific notation - with better performance - taken from pq2json
---
- None
**Features:**
- Decimal type - written as string
**Fixes:**
- None
> decimal writing

- connector/src/main/scala/com/microsoft/kusto/spark/authentication/KustoAuthentication.scala
- connector/src/main/scala/com/microsoft/kusto/spark/common/KustoOptions.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClientCache.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
- connector/src/test/scala/com/microsoft/kusto/spark/authentication/KustoAuthenticationTests.scala
- docs/Authentication.md
---
**Features:**
- Added a new option ("tokenProvider") to provide class path to a Token provider class that extends callable[String] - the java client is created with an instance of the class.
> Token provider authentication

- README.md
- connector/pom.xml
- connector/src/test/scala/com/microsoft/kusto/spark/KustoFilterTests.scala
- pom.xml
- samples/pom.xml
> spark 3 scala 2.12 support

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoClientTests.scala
- pom.xml
Azure Databricks with spark 3 is failing with the new ingestIfNotExists check for some reason - reported in azure databricks feedback system .
> Fix tags check for databricks

- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoQueryUtils.scala
- pom.xml
Different authentications should result in different relation as one might not have access or have different result accordingly
> Fix relation comparison to include authentication

- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
> Fix url with 'ingest'

- connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
- connector/src/test/scala/com/microsoft/kusto/spark/WriterTests.scala
- pom.xml
**Bug Fix **
- Existing table schema build
> Existing table schema build fix

- connector/pom.xml
- connector/src/main/scala/com/microsoft/kusto/spark/authentication/DeviceAuthentication.scala
- connector/src/main/scala/com/microsoft/kusto/spark/authentication/KustoAuthentication.scala
- connector/src/main/scala/com/microsoft/kusto/spark/common/KustoOptions.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoCsvSerializationUtils.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/DefaultSource.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoResponseDeserializer.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ContainerProvider.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/DataTypeMapping.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KeyVaultADALAuthenticator.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoAzureFsSetupCache.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoBlobStorageUtils.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClientCache.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoConstants.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
- docs/Authentication.md
- pom.xml
**Fixes:**
- Exclude conflicting dependencies
> Dependencies and some styling

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
- docs/KustoSink.md
- docs/KustoSource.md
**Features:**
- Use policy Auto delete instead of checking occasionally for lost tables
> Auto delete tables

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/RowCSVWriterUtils.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkBatchE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/WriterTests.scala
Timestamp accuracy is not achieved using the current date formatter 
---
**Features:**
- Timestamp accuracy is not achieved using the current date formatter
> Timestamp accuracy

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoClientTests.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceTests.scala
- pom.xml
Some nit changes included 
**Fixes:**
- Use same ClientRequestProperties to all commands
** Features **
- Allow url to include "ingest-"
> Use same ClientRequestProperties to all commands 

- samples/src/main/python/pyKusto.py
> Document customSchema

- connector/pom.xml
Fix assembly:single build plugin
> fix build single

- connector/pom.xml
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoFilter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
- connector/src/main/scala/com/microsoft/kusto/spark/exceptions/FailedOperationException.scala
- connector/src/main/scala/com/microsoft/kusto/spark/exceptions/RetriesExhaustedException.scala
- connector/src/main/scala/com/microsoft/kusto/spark/exceptions/SchemaMatchException.scala
- connector/src/main/scala/com/microsoft/kusto/spark/exceptions/TimeoutAwaitingPendingOperationException.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoIngestionUtils.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkSchemaAdjustmentE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
- pom.xml
Async merge so that it doesnt need to keep connection
> Async merge

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
If creation time is configured no need to use retention policy
> Remove retention policy if not needed

- README.md
Adding configuration example for how to use with SBT (commonly used with Spark projects), as well as a small formatting change for the other samples.
Small update to README
> Adding SBT example and a touch of formatting

- README.md
- connector/javadoc/readme.md
- connector/scalastyle_config.xml
- connector/src/main/scala/com/microsoft/kusto/spark/common/KustoOptions.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/DefaultSource.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoReader.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoSourceOptions.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/TransientStorageParameters.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KeyVaultUtils.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoBlobStorageUtils.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoBlobAccessE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoPruneAndFilterE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceTests.scala
- docs/Authentication.md
- docs/KustoSink.md
- docs/KustoSource.md
- docs/Spark-Kusto DataTypes mapping.md
- samples/src/main/python/SynapseSample.py
- samples/src/main/python/pyKusto.py
- samples/src/main/scala/KustoConnectorDemo.scala
- samples/src/main/scala/SparkStreamingKustoSink.scala
---
- None
**Features:**
- None
**Fixes:**
- None
> Merge from master

- README.md
- pom.xml
Upgrade Connector version from 2.9.3 to 3.0.0
> Upgrade Connector version from 2.9.3 to 3.0.0

- samples/src/main/python/SynapsePythonSDK.py
---
- None
**Features:**
- None
**Fixes:**
- None
> Python sdk synapse Authentication sample

- connector/src/main/scala/com/microsoft/kusto/spark/authentication/DeviceAuthentication.scala
- connector/src/main/scala/com/microsoft/kusto/spark/common/KustoOptions.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoSinkOptions.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoSourceOptions.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClient.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoClientCache.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoClientTests.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceTests.scala
- pom.xml
New option to set ingestion uri - in case it cannot be deduced from engine url
> Ingestion URI new option

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoIngestionUtils.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkSchemaAdjustmentE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoTestUtils.scala
* Creates an identity mapping in CSV in the order of columns when create table and GenerateCsvMapping is specified
**Fixes:**
- [Issue 260](https://github.com/Azure/azure-kusto-spark/issues/260)
> Fix Issue 260

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ExtendedKustoClient.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
> Fix Queued mode

- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoResponseDeserializer.scala
Added fix for issue: #266 
---
- None
**Features:**
- None
**Fixes:**
-  #266
> Maintaining Timestamp precision while reading

- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoResponseDeserializer.scala
- connector/src/test/resources/TestData/json/query-results-v1.json
- connector/src/test/resources/TestData/json/query-results-v2.json
- connector/src/test/scala/com/microsoft/kusto/spark/datasource/KustoResponseDeserializerTest.scala
Failed reading
print toreal(1.9),todecimal(1111111111.1111111111)
> Bugfix/Cast to double from decimal and 

- README.md
- pom.xml
version change to 3.1.7
---
- None
**Features:**
- None
**Fixes:**
- None
> version change to 3.1.7

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/FinalizeHelper.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ExtendedKustoClient.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkStreamingE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
- docs/KustoSink.md
- docs/KustoSource.md
- pom.xml
Was not handling failed drop tags
> Bugfix/Hidden option 'dedup' error handling

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/FinalizeHelper.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ExtendedKustoClient.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
- docs/KustoSink.md
Better retry for drop tags and async operations (could use it later in extents move .. or any async operation that permanent failure is considered transient)
> Drop tags retry

- README.md
- pom.xml
_[Changes for new version]_
---
> version change

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/FinalizeHelper.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/CslCommandsGenerator.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ExtendedKustoClient.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
_Improved performance by providing timerange to .move extents_
---
- None
**Features:**
- None
**Fixes:**
- None
> * Added support for .move extents time range

- README.md
- pom.xml
---
- None
**Features:**
- None
**Fixes:**
- None
> *version change to 3.1.12 for release

- connector/src/main/scala/com/microsoft/kusto/spark/authentication/KustoAuthentication.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/TransientStorageParameters.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoConstants.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceTests.scala
- connector/src/test/scala/com/microsoft/kusto/spark/authentication/KustoAuthenticationTests.scala
- connector/src/test/scala/com/microsoft/kusto/spark/datasource/TransientStorageParametersTest.scala
---
- None
**Features:**
- None
**Fixes:**
- #294
> Prevent credentials from printing as plain text

- README.md
- pom.xml
---
- None
**Features:**
- None
**Fixes:**
- None
> version change to 3.1.13

- connector/src/main/scala/com/microsoft/kusto/spark/datasource/TransientStorageParameters.scala
New  storage with Partitioned DNS has different url (the dns is partitioned ..)
> Sas url support for new storage

- README.md
- pom.xml
---
- None
**Features:**
- None
**Fixes:**
- None
> Version chage 4.0.1

- connector/pom.xml
- pom.xml
* lib changes
_updated jackson databind that contained vulnerabilities_
---
- None
**Features:**
- None
**Fixes:**
- None
> Lib fixes and removed CVE

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ContainerProvider.scala
- connector/src/test/scala/com/microsoft/kusto/spark/utils/ContainerProviderTest.scala
Fix the issue where the exception is not propagated in case of Queued Mode
---
Will need to be cherrypicked for 2.4 as well as 4.x versions
> * Fix the bug with exception not propagated

- README.md
---
- None
**Features:**
- None
**Fixes:**
- None
> readme version change

- README.md
---
- None
**Features:**
- None
**Fixes:**
- None
> readme Note change

- README.md
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ContainerProvider.scala
- connector/src/test/scala/com/microsoft/kusto/spark/utils/ContainerProviderTest.scala
- pom.xml
---
- None
**Features:**
- None
**Fixes:**
- None
> 2.4 jdk8 merge

- README.md
- connector/pom.xml
- pom.xml
---
- None
**Features:**
- None
**Fixes:**
- None
> java sdk version update to support fabric urls with jdk 8 support

- README.md
- pom.xml
---
- None
**Features:**
- None
**Fixes:**
- None
> version update 5.0.1

- connector/pom.xml
- pom.xml
Align with kusto data sdk versions and ADB runtime
> Bump versions

- README.md
- pom.xml
---
- None
**Features:**
- None
**Fixes:**
- None
> version change to 5.0.2

- connector/src/main/scala/com/microsoft/kusto/spark/utils/ContainerProvider.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ExtendedKustoClient.scala
- connector/src/test/scala/com/microsoft/kusto/spark/utils/ContainerProviderTest.scala
- pom.xml
This fixes the export containers implementation.
---
- None
**Features:**
- None
> [bugfix]  export containers path

- README.md
- connector/pom.xml
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ContainerProvider.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ExtendedKustoClient.scala
- connector/src/test/scala/com/microsoft/kusto/spark/WriterTests.scala
- connector/src/test/scala/com/microsoft/kusto/spark/utils/ContainerProviderTest.scala
- pom.xml
Shade libraries used in the connector
---
- None
**Features:**
- Smarter resources usage by newer SDK
**Fixes:**
- [338](https://github.com/Azure/azure-kusto-spark/issues/338)
> Shade libraries and add report statuses for ingestion 

- connector/pom.xml
- pom.xml
The reason shaded jar was working was because of the wrong Azure BOM version. When the azure BOM was reversed, the error was pertinent. This meant that the shading exercise did not work for some reason
Till we can get to it , making a new build that works for users
> *Revert changes in the shaded pom

- README.md
- connector/pom.xml
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ContainerProvider.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ExtendedKustoClient.scala
- connector/src/test/scala/com/microsoft/kusto/spark/utils/ContainerProviderTest.scala
- pom.xml
---
- None
**Features:**
- None
**Fixes:**
- None
> Feature/2.4 Backport PR

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
- pom.xml
Pass Cloud info from driver to workers instead of service
---
- None
**Features:**
- None
**Fixes:**
- Reduce Cloud metadata fetch from service calls
- Bump SDK version 5.0.3
> Cloud info from driver

- README.md
- pom.xml
---
- None
**Features:**
- None
**Fixes:**
- None
> Version change to 5.0.4

- README.md
- pom.xml
---
- None
**Features:**
- None
**Fixes:**
- None
> version bump 5.0.5

- connector/pom.xml
- pom.xml
This fixes the classNotFound error, that comes with maven import of the connector ( note: works well with manual jar upload)
---
- None
**Features:**
- None
**Fixes:**
- None
> [Bugfix] Excluded included correct msal lib

- README.md
- pom.xml
---
- None
**Features:**
- None
**Fixes:**
- None
> version Bump 5.0.6

- .github/workflows/build.yml
- connector/pom.xml
- connector/src/main/scala/com/microsoft/kusto/spark/exceptions/NoStorageContainersException.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ContainerProvider.scala
- connector/src/test/scala/com/microsoft/kusto/spark/ExtendedKustoClientTests.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkStreamingE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/utils/ContainerProviderTest.scala
- connector/src/test/scala/com/microsoft/kusto/spark/utils/KustoAzureFsSetupCacheTest.scala
- pom.xml
---
- None
**Features:**
- None
**Fixes:**
- None
> [Spark 2.4] Retry GetIngestion Resources backporting

- .github/workflows/build.yml
> * Update build file for publish step

- .github/workflows/build.yml
- connector/pom.xml
- connector/src/test/scala/com/microsoft/kusto/spark/KustoAuthenticationTestE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoBlobAccessE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoPruneAndFilterE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkBatchE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkSchemaAdjustmentE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkStreamingE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSourceE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoTestUtils.scala
- pom.xml
---
- None
**Features:**
- None
**Fixes:**
- None
> * Remove secrets from the repo for tests

- .gitignore
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/RowCSVWriterUtils.scala
- connector/src/test/scala/com/microsoft/kusto/spark/WriterTests.scala
- docs/Spark-Kusto DataTypes mapping.md
- pom.xml
cherry picked from https://github.com/Azure/azure-kusto-spark/pull/370
> rebased : Handle spark's `BinaryType`

- .github/workflows/release.yml
Changes for secret-less build and release.
> [feature]: Access token-based release

- connector/pom.xml
- pom.xml
This PR resolves, MSAL lib conflicting with ADB environments'
---
- None
**Features:**
- None
**Fixes:**
- None
> MSAL Lib conflict issue fix 

- pom.xml
Upgrade Java SDK
---
Upgrading to the latest SDK
- None
**Features:**
- None
**Fixes:**
- Update libs
> * Upgrade SDK version

- docs/KustoSource.md
Update documentation and security for Kusto source
> * Update documentation for source

- README.md
- connector/pom.xml
- connector/stripDependencyReducedPom.xsl
- pom.xml
There was an MSAL issue : 
git push --set-upstream origin bugfix/UpgradeMSALLib](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/806)
This fixes this issue that was reported
> * Create a uber jar for maven

- README.md
- pom.xml
* Update README
Change packaging to use self contained Uber jars
---
Future releases will use uber jar based deployment and release to maven
- Change packaging to use self contained Uber jars
**Fixes:**
- Fix issues where dependency conflicts arise because of library conflicts
> *Update version to remove snapshot

- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- pom.xml
---
- None
**Features:**
- None
**Fixes:**
- None
> * Ingest at the last for dup blobs option

- pom.xml
> * Update Kusto lib versions

- .github/workflows/release.yml
---
- None
**Features:**
- None
**Fixes:**
- None
> [bugfix]: Release pipeline changes

- connector/pom.xml
- pom.xml
---
- None
**Features:**
- None
**Fixes:**
- None
> revert: Revert Pom to v5.2.3

- connector/pom.xml
- connector/src/main/scala/com/microsoft/kusto/spark/common/KustoOptions.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/FinalizeHelper.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoSinkOptions.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasink/KustoWriter.scala
- connector/src/main/scala/com/microsoft/kusto/spark/datasource/KustoRelation.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/ExtendedKustoClient.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoConstants.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoCustomDebugWriteOptions.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoIngestionUtils.scala
- connector/src/test/scala/com/microsoft/kusto/spark/ExtendedKustoClientTests.scala
- connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkBatchE2E.scala
- connector/src/test/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtilsTest.scala
- connector/src/test/scala/com/microsoft/kusto/spark/utils/KustoIngestionUtilsSpec.scala
- connector/src/test/scala/com/microsoft/kusto/spark/utils/KustoIngestionUtilsTest.scala
- pom.xml
Add a developer option to add source location and source line
> Add a custom transform for SourceLocation

- connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoDataSourceUtils.scala
Add a small change to print the exception in case of polling failure from Kusto
> * Add error for transient failure
